/** @type {import('prettier').Config} */
module.exports = {
  endOfLine: "lf",
  semi: false,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "es5",
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "^(next/(.*)$)|^(next$)",
    "^@fortawesome/(.*)$",
    "<THIRD_PARTY_MODULES>",
    "",
    "^types$",
    "^types/(.*)$",
    "^components/(.*)$",
    "^styles/(.*)$",
    "^hooks/?(.*)$",
    "",
    "^lib/(.*)$",
    "^utils/(.*)$",
    "^data/(.*)$",
    "",
    "^[./]",
  ],
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  plugins: ["@ianvs/prettier-plugin-sort-imports"],
}
