import { Container, Text } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'

import { DrawerExample } from '../components/Drawer'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* TODO: Change to a Layout */}
      <Container
        display={'flex'}
        flexDirection={'column'}
        justifyContent={'center'}
      >
        {/* Array Syntax for responsive styling: https://chakra-ui.com/docs/styled-system/responsive-styles */}
        {/* sm, md, lg, xl, 2xl */}
        <Text fontSize={['sm', 'md', 'xl']} mx={'auto'} my={2}>
          Work in Progress...
        </Text>
        <DrawerExample />

        {/* TODO: Add Blog Posts */}
        {/* Blog Post Container */}
        {/* Hero Blog Post */}
        {/* Additional Blog Posts (mapped, max 4) */}
      </Container>
    </>
  )
}

export default Home
